logging:
  level:
    io.micrometer.tracing: DEBUG
    io.opentelemetry.exporter.otlp: DEBUG
#--------------------------------------------------------
# Server
#--------------------------------------------------------  
server:
    port: 8080 
    servlet: 
        session: 
            persistent: false
    http2:
        enabled: true
    compression:
        enabled: true
        mime-types: application/json

spring:
    main:
        web-application-type: reactive
    codec:
        max-in-memory-size: -1 # Remove buffer limits
    cloud:
        gateway:
            httpclient:
                connect-timeout: 600000    
                response-timeout: 600s  # 180s for long polls                
            server:
                webflux: 
                    globalcors:
                        add-to-simple-url-handler-mapping: true 
                        cors-configurations:
                            '[/**]':
                                allowedOrigins: "http://localhost:5173" #local
                                #allowedOrigins: "https://xxxxxxxx"  #production
                                allowedHeaders: "Authorization,Content-Type,Accept"
                                allowedMethods:
                                  - GET
                                  - POST
                                  - DELETE
                                  - PUT
                                  - OPTIONS                                  
                                  - PATCH

# --------------------------------------------------------------
# Enable Monitoring
# --------------------------------------------------------------
management:
    endpoints:
        web:
            exposure: 
                include: gateway,health,metrics,circuitbreakers,circuitbreakerevents
        health:
            show-details: always
    health: 
        circuitbreakers:
            enabled: true
            
