#--------------------------------------------------------
#  disable security completely
#--------------------------------------------------------
security:
  basic:
    enabled: false

#--------------------------------------------------------
#  Tracing  across Thimarix microservices  - Zipkin
#--------------------------------------------------------
tracing:
  url: http://localhost:4318/v1/traces

management:
  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

  otlp:
    metrics:
      export:
        enabled: false
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
#--------------------------------------------------------
# Eureka Client
#--------------------------------------------------------  
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: ${eureka_url:http://localhost:8761/eureka}           
    instance: 
        hostname: localhost
#--------------------------------------------------------
# CORS Configuration
#--------------------------------------------------------
cors:
    origins: http://localhost:5173   #local
    #origins: https://xxxxxxx     #production
    methods: POST,PUT,GET,OPTIONS,DELETE,PATCH
    headers: Authorization,Content-Type,Accept

#--------------------------------------------------------
# Custom properties
#--------------------------------------------------------
app:
    loadbalance:
        authentication: lb://AUTHENTICATION-SERVICE
